config/routes.rb
Rails.application.routes.draw do

  scope "admin", :module => :admin, :as => "admin" do

    match "/" => "dashboard#show", :as => "dashboard"
    match "user_guide" => "base#user_guide"

    if Typus.authentication == :session
      resource :session, :only => [:new, :create], :controller => :session do
        get :destroy, :as => "destroy"
      end

      resources :account, :only => [:new, :create, :show, :forgot_password] do
        collection do
          get :forgot_password
          post :send_password
        end
      end
    end

    Typus.models.map { |i| i.to_resource }.each do |resource|
      match "#{resource}(/:action(/:id(.:format)))", :controller => resource
    end

    Typus.resources.map { |i| i.underscore }.each do |resource|
      match "#{resource}(/:action(/:id(.:format)))", :controller => resource
    end

  end

end

app/controllers/admin/dashboard_controller.rb
class Admin::DashboardController < Admin::BaseController

  def show
  end

end

app/helpers/admin/dashboard_helper.rb
module Admin
  module DashboardHelper

    def resources(admin_user)
      available = Typus.resources.delete_if { |r| !(admin_user.is_a?(FakeUser) || admin_user.resources.include?(r)) }
      render "admin/helpers/dashboard/resources", :resources => available
    end

  end
end

app/views/admin/dashboard/_applications.html.erb
<% admin_user.applications.each do |app| %>

  <table>

    <thead>
      <tr>
        <th><%= Typus::I18n.t(app) %></th>
      </tr>
    </thead>

    <% admin_user.application(app).each do |model| %>

      <%
        klass = model.typus_constantize
        klass_human_name = klass.model_name.human.pluralize
        admin_items_path = { :controller => "/admin/#{klass.to_resource}" }
      %>

      <tr class="<%= cycle("even", "odd") %>">
        <td>
          <%= link_to klass_human_name, admin_items_path %>
        </td>
      </tr>

    <% end %>

  </table>

<% end %>

app/views/admin/dashboard/_sidebar.html.erb
<h2>Welcome!</h2>

<p>If you need help don't hesitate in joining the <%= link_to 'mailing list', 'http://groups.google.com/group/typus' %> or use the provided <%= link_to "user guide", admin_user_guide_path %>.</p>

<p>Replace this sidebar dropping a file named <code>_sidebar.html.erb</code> on the <code>app/views/admin/dashboard</code> folder.</p>

app/views/admin/dashboard/show.html.erb
<%
  page_title = Typus::I18n.t("Dashboard")
  title(page_title)
%>

<% content_for :sidebar do %>
  <%= render "sidebar" %>
<% end %>

<h2>
  <%= page_title %>
</h2>

<% if admin_user.applications.any? %>
  <%= render 'applications' %>
<% else %>
  <div class="notice">
    No applications detected.
  </div>
<% end %>

<%= resources(admin_user) %>

app/views/admin/dashboard/styles.html.erb
<% content_for :sidebar do %>

  <h2>Header (h2) <small>Small <a href="#">link</a></small></h2>

  <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
  tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
  quis <a href="#">nostrud exercitation</a> ullamco laboris nisi ut aliquip ex
  ea commodo consequat.</p>

  <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
  tempor incididunt ut labore</p>

  <h3>Header (h3)</h3>

  <ul>
    <li>Lorem incididunt</li>
    <li>Lorem incididunt</li>
    <li>Lorem incididunt</li>
  </ul>

  <h3><a href="#">Header (h3)</a></h3>

  <ul>
    <li><a href="#">Lorem incididunt</a></li>
    <li><a href="#">Lorem incididunt</a></li>
    <li>Lorem incididunt</li>
  </ul>

<% end %>

<h2>Header (h2) <small>Small <a href="#">link</a></small></h2>

<p>
Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat
non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
</p>

<blockquote>
  <p>
  Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
  tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
  quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
  consequat.
  </p>
  <p>
  Duis aute irure dolor in reprehenderit in voluptate velit esse
  cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat
  non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
  </p>
</blockquote>

<pre>
Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat
non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
</pre>

<p>
Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
consequat.
</p>

<p><a href="#">Link to self</a></p>

<h3>Header (h3)</h3>

<p>
Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
consequat.
</p>

<h2>Boxes</h2>

<div class="box">
  <p>
  Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
  tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
  quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
  consequat.
  </p>
</div>

<div class="box">
  <h3>Header (h3)</h3>
  <ul>
    <li>Lorem ipsum dolor sit amet</li>
    <li>Duis aute irure dolor in reprehenderit in voluptate</li>
    <li>Laboris nisi ut aliquip ex ea commodo</li>
  </ul>
</div>

<div class="box">
  <h3>Header (h3)</h3>
  <p>
  Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
  tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
  quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
  consequat.
  </p>
  <ul>
    <li>Lorem ipsum dolor sit amet</li>
    <li>Duis aute irure dolor in reprehenderit in voluptate</li>
    <li>Laboris nisi ut aliquip ex ea commodo</li>
  </ul>
</div>

<p>
Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
consequat.
</p>

<h2>Error Messages (h2)</h2>

<div id="flash" class="notice">
  <strong>Hey!</strong> Sample ui-state-highlight style.
</div>

<div id="flash" class="alert">
  <strong>Alert:</strong> Sample ui-state-error style.
</div>

<h2>Filters (h2)</h2>

<h3>Filters with a list inside (h3)</h3>

<div class="filters">
  <ul>
  <li>Filter</li>
  <li>Filter</li>
  </ul>
</div>

<h3>Filters with a paragraph inside (h3)</h3>

<div class="filters">
  <p>This is a paragraph.</p>
</div>

<h2>Forms (h2)</h2>

<p>This is how a form looks like.</p>